### ISSUE TITLE
Extend API to support doubles

### ISSUE THREAD

**Issue by mrpinkzh** [mrpinkzh/exas#4]

**Comment by binaryfr3ak** [comment]
i'll take that

**Comment by mrpinkzh** [comment]
fine for me

**Comment by binaryfr3ak** [comment]
is there a way to attach a issue to a user? if it is possible, please assign it to me :+1:

**Comment by binaryfr3ak** [comment]
Anyway - api already supports double datatype with integer code. My suggestion is to rename the namespace from Integers to Numbers.
